### ISSUE TITLE
Option to ignore undeclared child elements

### ISSUE THREAD

**Issue by joaopbnogueira** [tobywf/xml_dataclasses#3]
Hi Toby,

First of all, thanks for this great package, it was sorely missing from the python ecosystem.

When developing over it I realised that the deserialisation only works correctly if all returned XML elements and attributes are declared on the corresponding dataclass.

Because XML is extendable by nature, the classes can be a subset representation of the complete schema, therefore it would be nice to have the option to ignore unknown elements and attributes.

Pseudo example of crashing code:

```
@xml_dataclass
@dataclass
class Error:
    __ns__ = None
    code: Optional[ErrorCode] # element
    message: Optional[str] # attribute

<Error message="toast" details="xyz">
    <code>123</code>
    <extra>456</extra>
</Error>
```

Thanks!

**Comment by tobywf** [comment]
I think I mentioned this in the readme, it's a limitation for now. I do want this strict behaviour to be the default, but it should be straightforward to add a parameter to `load` for lenient operation. I've finally got some time, so I might have a go at this.
