### ISSUE TITLE
If I have a datetime field, how can I tell which format to use during xml conversion

### ISSUE THREAD

**Issue by CAMOBAP** [tobywf/xml_dataclasses#9]
I have a simple `dataclass`:

```python
import datetime
from dataclasses import dataclass
from xml_dataclasses import xml_dataclass
from typing import ClassVar


@xml_dataclass
@dataclass(frozen=True)
class Test:
    FORMAT: typing.ClassVar[str] = "%Y-%m-%d %H:%M"

    begins: datetime.datetime = None
    ends: datetime.datetime = None
    revision: datetime.datetime = None
```

How can I specify to use `FORMAT` during serizliation?

**Comment by tobywf** [comment]
See the README for supported types. If you would like to work on a type conversion feature, the wiki [has some questions](https://github.com/tobywf/xml_dataclasses/wiki/Type-conversion-design) that needs to be answered. I'd be happy to chat about a design if you propose one.
